---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---
```{r}
Vec1<- c(1:6)
Vec1
```

```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1
```

```{r}
Mat2 <- matrix(
  c("a","b","c","d"),2,2
)
Mat2
class(Mat2)
typeof(Mat2)
a<-Mat2[[1]]
c<-Mat2[[3]]
a
c
```

```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
typeof(StuDF)
class(StuDF)
```
#data.frame()遇到變數輸入為character class時，內定會被轉成factor。
```{r}
StuDF[[2]][[3]]
```

```{r}
class(StuDF$姓名)
```

```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
class(StuDF2$姓名)
```


```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
as.data.frame(StuList) -> StuDF3

class(StuDF3)
```

```{r}
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```

```{r}
StuDF4
```

```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
chosenLETTERS1 <- LETTERS[1:9]
matobj2 <- matrix(chosenLETTERS1,3,3)
matobj2
```

```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m)
```

```{r}
matObj1
matObj1[[8]]
```

```{r}
matObj1[3,2]
```

```{r}
matObj1
matObj1[c(1,4),c(2,3)]
matObj1[c(T,F,F,T,F),c(F,T,T)]
```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
#取出性別&學分數
```{r}
classSurvey[,c(4,5)]
classSurvey[c(1:60),c(4,5)]
```

```{r}
classSurvey[4:5]
classSurvey[c(1:60),c(4,5)]
classSurvey[c("性別","本學期學分數")]
```

```{r}
classSurvey[logical_index,] <-classSurvey[4] == "女"
```

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1) #NULL=沒有名字
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6') #也可以用雙引號
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

只改col2的名稱
```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2
```
改col2,3的名稱
```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <-list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)　
b[[3]] <-"FALSE"
b[[5]] <-"7"
b$新元素<- "4"
b
```
使用"元素名稱"創新元素
```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(lubridate)
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
取出「期間」變數轉成date class。
```{r}
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis <-exData3$期間 >=ymd("1997-06-01") & exData3$期間 <=ymd("1998-12-01")
e\
```

```{r}
exData3$isAsiaCrisis <- exData3$期間 >= ymd("1997-06-01") & exData3$期間 <= ymd("1998-12-01")
class(exData3$isAsiaCrisis)
```

```{r}
exData3[exData3$isAsiaCrisis==T,]
```

```{r}
logiAsiaCrisis <- exData3$isAsiaCrisis
exData3[logiAsiaCrisis, ]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
transcriptDataFinal[transcriptDataFinal$學號 =="92aS67fee",]
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
class(utility_cobb_douglass)
```
```{r}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
function1 <- function(x,.alpha){
  value <- x+.alpha
  return(value)
}

class(function1)
```

```{r}
supply_fun <- function(a,b,P){  
  Qs <-a+b*P
  return(Qs)
}

demand_fun<- function(c,d,P){
  Qd<-c-d*P
  return(Qd) 
}
```

```{r}

supply_fun(0,1,1)
demand_fun(5,1,1)
```

