---
title: '2015-05-22'
author: "莊品婕"
date: "5/22/2019"
output: html_document
---

## midterm 6.2

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
library(lubridate)
```

```{r}
(invoiceList$訂單時區=="America/New_York") -> nyLogical #TRUE/FALSE
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical #TRUE/FALCE

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical], #只取這是TRUE部分
          tz="America/New_York") ->nyDateTime

invoiceList$UTC時間[nyLogical] <- #挑出紐約時間換成UTC時間
  with_tz(nyDateTime,tzone="UTC")

ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical], #只取這是TRUE部分
          tz="Asia/Taipei") ->tpDatetime

invoiceList$UTC時間[tpLogical] <-
  with_tz(tpDatetime,tzone="UTC")

invoiceList 
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")

gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```

```{r}
ymd_hms_tzChange("1973-02-21 12:05:22"
                 "America/New_York"
                 "Asia/Taipei")
```

請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示。
```{r}
AmerICATIME <- ymd_hms("1973-02-21 12:05:22",tz="America/New_York")
AmerICATIME1 <-with_tz(AmerICATIME,tzone = "Asia/Taipei")
AmerICATIME1
```

```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input,tz=fromTzone)
  answer <- with_tz(time1,tzone = toTzone)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```

```{r}
library(lubridate)
ymd_hms("1973-02-21 12:05:22", tz="America/New_York") -> fromDateTime
with_tz(fromDateTime,tzone="Asia/Taipei") -> toDateTime
toDateTime

ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input,tz=fromTzone)
  answer <- with_tz(time1,tzone = toTzone)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```

```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates

twDates
```

```{r}
library(stringr); library(lubridate)      #前面都是民國，加號是們的意思(數字們)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)") #取緊接著月的數字們
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
yyyymmdd
```

```{r}
date_convert_twYM <-function(twDates){
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)") #取緊接著月的數字們
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
 return(yyyymmdd)
}
date_convert_twYM(twDates)
```

##預設
```{r}
utility_cobb_douglass2 <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```

```{r}
utility_cobb_douglass2(1,2) # 使用預設值
utility_cobb_douglass2(1,2,0.5,0.8) # 自定參數值
```

##先前的date_convert_twYM()函數一律把年月資料加上「01」日，請改寫函數讓“01”為「日」的預設值
```{r}
date_convert_twYM <-function(twDates,dd="01"){
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)") #取緊接著月的數字們
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  return(yyyymmdd)
}
date_convert_twYM(twDates,dd="30")
```

```{r}
library(lubridate)

#沒有input
now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
##沒有return，cat是在螢幕顯現
```


```{r}
now2()
now2() ->xx
```

```{r}
textbookURL<-function(){
  browseURL("https://via.hypothes.is/https://bookdown.org/tpemartin/ntpu-programming-for-data-science/")
}
textbookURL()
```


```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```


```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```


```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```

```{r}
demand_supply_fun<- function(P,a,b,c,d){
  Qs <-a+b*P
  Qd <-c-d*P
  ES <- Qs-Qd
  
  return(
    list(
      供給量=Qs,
      需求量=Qd,
      超額供給量=ES
    )
  )
}

```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```

```{r}
a<-0
b<-1
supply_fun <- function(P,a,b){
  Qs <- a+b*P
  return(Qs)
}
supply_fun(P=-1,0,1)
```

```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs) #P>0才會執行RETURN
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```

```{r}
a <-  readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
} else {
  print("a不為負值")
}
```

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值")  # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```

```{r}
gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```


```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID %in% transcriptDataFinal$學號){
  return(GPA)
  }else{
      message("NO SEARCH ID")
    }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
   transcriptDataFinal$學號==studentID -> logiChosenStudent
   subSample <- transcriptDataFinal[logiChosenStudent,]
   sum(subSample$學期成績*subSample$學分數)/
     sum(subSample$學分數) -> GPA
   return(GPA)
 } else{
   message("查無此學號")
    }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P必需大於等於",-a/b,"(即-a/b值)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
fizzbuzz<- function(a){
  if(a%%3==0){
      return("fizz")}
  else if(a%%5==0)
      {return("buzz")}
  else if(a%%3==0 &a%%5==0)
      {return("fizzbuzz")}
}
fizzbuzz(5)
fizzbuzz(45)
```

```{r}
fizzbuzz <- function(number){
  if(number %% 15== 0){
    return("fizzbuzz")}
    else if(number%% 3 ==0){
      return("fizz")
    }else if (number%% 5 == 0){
      return("buzz")
    }else {
      return(number)
    }
}
fizzbuzz(5)
fizzbuzz(45)
```

```{r}
fizzbuzz<-function(x){
  if(x%%3==0&x%%5!=0){
    print("fizz")
  }
  else if(x%%5==0&x%%3!=0){
    print("buzz")
  }
  else if(x%%5==0&x%%3==0){
    print("fizzbuzz")
  }
  else{
    print(x)
  }
}
fizzbuzz(5)
fizzbuzz(45)
```


## any all
```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
```


要每個a元素都>2, 使用all()
```{r}
a
a>2
all(a>2)
any(a>2)
```

## environment
```{r}
a <- 3

testfun <- function(x){
  y <- a/4
  output <- x*y
  return(output)
}


testfun(2)

a <- 4
testfun(2)
```

