---
title: '2019-04-17'
author: "林茂廷"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
```

```{r}
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}

studentRecord <-
  list(
    學號="410073058",
``` 

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```
 
```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

```{r}
plasticContainer[[2]]
plasticContainer[["redBox"]]
```

```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
plasticContainer[["greenBox"]][[1]]
```

```{r}
y <- plasticContainer[["redBox"]]
y[[3]]
plasticContainer[["redBox"]][[3]]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單[["個經"]]
成績單[[1]]
```

```{r}
studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][[3]]
studentRecord[["學年平均成績"]][["三年級"]]
```

```{r}
plasticContainer[c(1,2)]
plasticContainer[c("greenBox","redBox")]
```

```{r}
plasticContainer

extract1 <- plasticContainer[c("greenBox")]
extract1
extract2 <- plasticContainer[[c("greenBox")]]
extract2

extract1[[1]][[1]]
extract2[1]
extract2[[1]]
```

```{r}
plasticContainer

length(plasticContainer)
plasticContainer[c(T,F,T)]
```

```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```

```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```

```{r}
your_github_username <- "evia1999"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```

```{r}
commitCheckStatement
```

```{r}
commitCheck
```

```{r}
commitCheck[[4]][[3]][[2]][[3]]
commitCheck[[4]][["commit"]][["committer"]][["date"]] ->commitdate
ymd_hms(commitdate) ->commitdate
with_tz(commitdate,tzone="Asia/Taipei")
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

```{r}
filmVotingData$Timestamp
filmVotingData[["Timestamp"]]
filmVotingData$`Timestamp`
```

```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數
```

```{r}
logiCorrect <-str_length(birthday)==8
logiCorrect
```

```{r}
favoriteTwo[logiCorrect] ->validfavoriteTwo
validfavoriteTwo
```
