---
title: '2019-03-27'
author: "莊品婕"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObject
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")

twDateTime
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")

LisbonDateTime
```

```{r}
typeof((twDateTime))
as.double((twDateTime))
as.double(LisbonDateTime)
```

```{r}
dtObject<-ymd_hms("1999-07-01 03:47:23") ㄎ
```

```{r}
twDateTime <- ymd_hms("1999-07-01 03:47:23", tz="Asia/Taipei")

twDateTime
```

```{r}
VientianeDateTime <- with_tz(twDateTime,tzone="Asia/Vientiane")

VientianeDateTime
```

```{r}
FaroeDateTime <- with_tz(twDateTime,tzone="Atlantic/Faroe")

FaroeDateTime
```

```{r}
typeof(twDateTime)
as.double(twDateTime)
as.double(VientianeDateTime)
as.double(FaroeDateTime)
```

```{r}
dtObject<- mdy_hms("3/14/2019 08:18:47")
dtObject
```

```{r}
twDateTime<- mdy_hms("3/14/2019 08:18:47")

twDateTime
```

```{r}
lastyear<- ymd("2018-09-11")
lastyear
```

```{r}
fewdaysago<- mdy("March 3, 2019")
fewdaysago
```

```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02")) 
as.integer(ymd("2019-03-11")) 
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```

```{r}
a-b
a+b
a*b
a/b
```

```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
a+aL
class(a+aL)

aL-bL
class(aL-bL)

```

```{r}
a
a+5
a-2
a*4
a/2
```

```{r}
a^b
a %% b
```

```{r}
b^bL
aL%%b
```

```{r}
twDateTime 
twDateTime+1
```

```{r}
twDateTime 
twDateTime-2
```

```{r}
future<-ymd("2019-08-11")
future
```

```{r}
past<-ymd("2000-02-01")
past
```

```{r}
future-past
class(future-past)
```

```{r}
startingDate <- ymd("2000-02-17")
```

```{r}
startingDate + years(1)
```

```{r}
startingDate + dyears(1)
```

```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x <= y
x == y
x > y
```

```{r}
x2
y2
x2 == y2
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3
y3
x3 == y3
x3 != y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4
y4
x4 %in% y4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5
y5
x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
x2
y2
x2 == y2
```

```{r}
is.na(x2)
is.na(y2)
```

```{r}
sum(x2)
sum(x2,na.rm = TRUE)
```

```{r}
0/0
```

